spring.application.name=myAdvice
spring.datasource.url=jdbc:mysql://localhost:3306/myadvicedatabase
spring.datasource.username=usermyadvice
spring.datasource.password=Comp2800!passWord!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true